### PR TITLE
Update ferros/buffer to version 5

### PR DESCRIPTION
**Pull request by venik**
Hi,

Sorry previous PR #67 contained wrong email. Is it possible to update ferros/buffer to version 5? Problem is that versions 4.X refers to global

```
Buffer.TYPED_ARRAY_SUPPORT = global.TYPED_ARRAY_SUPPORT !== undefined
  ? global.TYPED_ARRAY_SUPPORT
  : typedArraySupport()
```
which leads to #60 and #31

this patch has fixed this problem and version 5.X works just fine.

We used shrinkwrap to work it around, but would be better to have updated version of the node-libs-browser (npm-shrinkwrap.json):

```
{
  "dependencies": {
    "webpack": {
      "version": "3.3.0",
      "dependencies": {
        "node-libs-browser": {
          "version": "2.0.0",
          "dependencies": {
            "buffer": {
              "version": "5.0.7"
            }
          }
        }
      }
    }
  }
}
```

Thanks in advance!

### CODE REVIEW

**Comment by jhnns** [comment]
This is a breaking change, see https://github.com/feross/buffer/commit/5daca86b7cd5d2b8ccb167534d47421029f639e9#commitcomment-19698936. We will pull this in with the next major version bump. Users that still need to support IE9 and IE10 can use a [polyfill](https://github.com/substack/typedarray).

**Comment by venik** [comment]
@jhnns thx for the reply!

**Comment by crabicode** [comment]
Buffer v4 fails at simple case fails at simple `Buffer.alloc(1, !!true)`, but works in any nodejs env. Simple like it is time to move forward

**Comment by flipflopsimsommer** [comment]
any plans when this will be merged?

**Comment by mvasilkov** [comment]
Hi, can we please integrate this?

**Comment by sokra** [comment]
This library is deprecated and won't accept Pull Requests that include Breaking Changes or new Features. Only bugfixes are accepted.

We can't add a breaking change to webpack 4.

webpack 5 will no longer use `node-libs-browser`, but allows you to use any buffer version.

**Pull request closed without merging**
