### PR TITLE
feat(libs): replace `http-browserify` with `stream-http`.

### LINKED ISSUE #38: Use stream-http
Browserify has stopped using `http-browserify` and moved to [`stream-http`](https://www.npmjs.com/package/stream-http) which actually supports true response streaming and has lots of bug fixes.

webpack should probably switch over too.

This would fix [this bug](https://github.com/feross/webtorrent/issues/768#issuecomment-214949683) when WebTorrent is built with webpack.

cc @jhiesey

### PR DESCRIPTION
**Pull request by terinjokes**
Fixes #38.

### CODE REVIEW

**Comment by terinjokes** [comment]
@TheLarkInn If it's any consolation browserify switched to `stream-http` several versions ago, and it's a much more accurate implementation of the Node.js builtin. `http-browserify`, on the other hand, is unmaintained.

Is there another test I should be running on master other than "did it get bundled"?

**Comment by TheLarkInn** [comment]
Welp I think one would be npm link the dep to webpack on master, then run tests locally. I'd list that results here

**Comment by terinjokes** [comment]
@TheLarkInn Let me know if there are reasonable tests to contribute, either to this repo or to webpack. I didn't see any tests in webpack for the builtins.

**Comment by RomanGotsiy** [comment]
@terinjokes I believe https-browserify should be replaced with streem-http too.
Check out this issue substack/https-browserify#6. (Although it is closed, the issue itself is not resolved)

**Comment by terinjokes** [comment]
I commented on the above ticket.

**Comment by feross** [comment]
cc @jhiesey

**Comment by connor4312** [comment]
Getting this in would be fantastic! stream-http is much more featureful and has greater parity with the server-side version.

**Comment by dandv** [comment]
Any chance of merging this in?

**Comment by jhnns** [comment]
Thx @terinjokes. This looks good. Could you sign the CLA?

Sorry for taking so long, but switching these libraries is kind of risky because they provide an incredible big API surface to the user. Most of developers don't know this. However, since browserify is using it too, it's very safe – and it provides a consistent experience for webpack- and browserify-users.

**Comment by jhnns** [comment]
The PR was against node-libs-browser master which is 1.0.0. After merging this, I will try to backport most of the updates. @sokra told me, there was a breaking change in the buffer module or somewhere there, that's why he decided to release a new version but he can't remember it for sure.

**Comment by terinjokes** [comment]
@jhnns Per the CLA, can you first add a `LICENSE` file? The license listed in `package.json` is "MIT".

**Comment by jhnns** [comment]
Haha, good catch, thx. I added the MIT license.

**Comment by jhnns** [comment]
Thx @terinjokes 

We will probably update node-libs-browser also in webpack v1, see #45

**Comment by feross** [comment]
`stream-http` is still not being used with latest webpack because this isn't published to npm yet.

**Pull request merged**
