### PR TITLE
update process to 0.11

### PR DESCRIPTION
**Pull request by longlho**
`process@0.11` has a very important [fix](https://github.com/defunctzombie/node-process/pull/38) that fixes the queue being completely clogged when an error happens so can we bump it :(

@sokra

### CODE REVIEW

**Comment by Edmondton** [comment]
:+1:

**Comment by marturi** [comment]
:+1:

**Comment by jazzyblue** [comment]
:ship:

**Comment by DekusDenial** [comment]
:trophy:

**Comment by longlho** [comment]
ping @sokra

**Comment by sokra** [comment]
Thanks

**Pull request merged**
