### PR TITLE
chore: update stream-http

### PR DESCRIPTION
**Pull request by hugomrdias**

### CODE REVIEW

**Comment by hugomrdias** [comment]
Ping

**Comment by wmhilton** [comment]
:+1: I'm experiencing a lot of issues with Webpack bundling both v2 and v3 of readable-stream. Most of my dependencies (through2, split2) have switched to readable-stream@3 so now would be a good time to get Webpack on the readable-stream@3 horse as well.

(readable-stream@3 is a transitive dependency of stream-http@3)

**Comment by hugomrdias** [comment]
Ping

**Comment by sokra** [comment]
This is a breaking change so this can't be merged

**Pull request closed without merging**
