### PR TITLE
Update path-browserify to v1.

### PR DESCRIPTION
**Pull request by goto-bus-stop**
This version updates to the Node v10.3.0 API. **This change is breaking**,
because path methods now throw errors when called with arguments that are not
strings. Previously `path.dirname`, `path.basename` and `path.extname` did
not throw.

Change overview:
* Add `path.parse` and `path.format`.
* Add `path.posix` as an alias to `path`.
* Port tests from Node.js.

### CODE REVIEW

**Comment by wmhilton** [comment]
Ooooh! Ooooh! YAYAYAYAYAY!!!

**Comment by wmhilton** [comment]
Is there anything blocking this? I keep getting tripped by the lack of `path.posix` in Webpack's path module so this upgrade would be really nice.

**Comment by jshado1** [comment]
@evilebottnawi could you merge this please?

**Comment by evilebottnawi** [comment]
yep, in todo list, see on this in Monday, maybe we should update after stuff to for next major release

**Comment by evilebottnawi** [comment]
@jshado1 unfortunately, we can't update, for webpack it is breaking change, also `webpack@5` already doesn't add polyfills by default. Anyway i am open for idea how we can solve this

**Comment by goto-bus-stop** [comment]
@evilebottnawi there is another PR to update path-browserify to 0.0.1, which fixes the ReDOS vuln but doesn't introduce breaking changes: https://github.com/webpack/node-libs-browser/pull/89

**Comment by jshado1** [comment]
@evilebottnawi shouldn't the arguments already be strings? I suppose it technically would be breaking if enforced now.

Sorry, I don't understand your comment about polyfills.

**Comment by evilebottnawi** [comment]
@jshado1 webpack@5 doesn't add node polyfills by default, for webpack@4 it is breaking change

**Comment by sokra** [comment]
This library is deprecated and won't accept Pull Requests that include Breaking Changes or new Features. Only bugfixes are accepted.

**Comment by billiegoose** [comment]
the times, they are a-changin'

**Pull request closed without merging**
