### PR TITLE
feat: added memfs as fs browser implementation

### PR DESCRIPTION
**Pull request by streamich**

### CODE REVIEW

**Comment by streamich** [comment]
Are you serious @codacy/pr? All other strings there are with single quotes.

> Strings must use doublequote. (quotes)

**Comment by jhnns** [comment]
> Are you serious ? All other strings there are with single quotes.

Oops, sorry, seems like this is mis-configured. I've reverted it to single quotes to make it consistent with the rest :)

I'm discussing this addition with the rest of the team since it adds some weight to the webpack installation. Anyway, thanks for the PR 👍

**Comment by streamich** [comment]
Cool, if you use it, please use the latest version.

**Comment by jhnns** [comment]
> It should be added only to bundles that actually import fs module.

This is the case anyway. But the module is installed with every webpack installation although it is probably not used.

**Comment by streamich** [comment]
Oh, that's what you mean. If it is too big, I could theoretically bundle everything into a single `.js` file and remove `.ts` files in the NPM package.

**Comment by streamich** [comment]
Can you install packages that "shim" Node's internals only when they are actually used?

**Comment by jhnns** [comment]
> Can you install packages that "shim" Node's internals only when they are actually used?

Not really, webpack is not in charge of installing dependencies in the application... but I think it would be nice to provide a suggestion to webpack user's.

**Comment by streamich** [comment]
BTW, you could also replace `memory-fs` with this.

**Comment by sokra** [comment]
This library is deprecated and won't accept Pull Requests that include Breaking Changes or new Features. Only bugfixes are accepted.

**Pull request closed without merging**
