### PR TITLE
Bump os-browserify dependency to 0.3.0

### PR DESCRIPTION
**Pull request by bmeurer**
This fixes issue #66

### CODE REVIEW

**Comment by medialwerk** [comment]
When will the commit be included? :-)

**Comment by bmeurer** [comment]
@jhnns promised to take a look.

**Comment by jhnns** [comment]
Thanks 👍 
Shipped with `2.1.0` (should land in current webpack 3 installations)

**Comment by bmeurer** [comment]
Thank you!

**Comment by medialwerk** [comment]
Thanks!

**Pull request merged**
